---
#Install PostgreSQL 

- name: Install PostgreSQL server 
  package: 
    name: "{{ postgresql-server-package }}"
    state: present

- name: Install PostgreSQL contrib
  package: 
    name: "{{ postgresql-contrib-package }}" 
    state: present

- name: Run initdb
  command: /bin/postgresql-setup initdb 
  args:
    creates: /var/lib/pgsql/initdb.log
  when: ansible_os_family == "RedHat"

- name: Start the postgreSQL service
  service: 
    name: "postgresql" 
    enabled: true 
    state: started

