---
# Playbook for installing Hyrax IR Stack.

- name: Install Hyrax on local hosts.
  hosts: 127.0.0.1
  connection: local 
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_os_family }}.yml"
  roles:
    - hyrax
