---
# Playbook for installing Hyrax IR Stack.

- name: Install Hyrax on local hosts.
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_distribution }}.yml"
  roles:
    - postgresql
    - fedora4
    - redis
    - nginx
