---
# Setup Tomcat and Fedora4
- name: Ensure group "tomcat" exists with correct gid
  group:
    name: "{{ tomcat_group }}"
    state: present
    gid: 501

- name: Add the user 'tomcat' with a specific uid and a primary group of 'tomcat'
  user:
    name: "{{ tomcat_user }}"
    uid: 501
    state: present
    group: "{{ tomcat_group }}"

- name: Install Java 1.8 (OpenJDK)
  package:
    name: "{{ java_openjdk_package }}"
    state: present

- name: Enable package for Amazon Linux
  shell: "amazon-linux-extras enable tomcat8.5 && yum clean metadata"
  when: ansible_distribution == "Amazon"

- name: Install the Tomcat host manager and admin applications
  package:
    name: "{{ tomcat_admin_package }}"
    state: present

- name: Set setsebool nis_enabled on
  command: /usr/sbin/setsebool -P nis_enabled on
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: Set setsebool tomcat_can_network_connect_db on
  command: /usr/sbin/setsebool -P tomcat_can_network_connect_db on
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: Overwrite the Tomcat users file
  template:
    src: tomcat-users.xml
    dest: "{{ tomcat_users_conf_path }}"
    owner: root
    group: "{{ tomcat_group }}"
    mode: u=r,g=r,o=
  notify: restart tomcat

- name: Make Fedora 4 data directory
  file:
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    path: /opt/fcrepo-data

- name: Create the Fedora 4 tomcat conf file which sets JAVA_OPTS
  template:
    src: fedora4.conf
    dest: "{{ tomcat_fedora4_conf_path }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: u=rx,g=,o=
  notify: restart tomcat

- name: Download the Fedora 4 warfile
  get_url:
    url: "https://github.com/fcrepo4/fcrepo4/releases/download/fcrepo-{{ fedora4_version }}/fcrepo-webapp-{{ fedora4_version }}.war"
    dest: "{{ tomcat_fedora4_war_path }}"
    owner: root
    group: "{{ tomcat_group }}"
    mode: u=r,g=r,o=r
    checksum: "{{ fedora4_checksum }}"

- name: Start and enable the Tomcat service
  service:
    name: "{{ tomcat_service_name }}"
    state: started
    enabled: yes
