---
# Setup Tomcat and Fedora4

- name: Install Java 1.8 (OpenJDK)
  package:
    name: "{{ java_openjdk_package }}"
    state: present

- name: Install python postgresql module
  package:
    name: "{{ python_psycopg2_package }}"
    state: present

- name: Create the Fedora 4 database
  postgresql_db:
    name: fcrepo
    state: present
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

- name: Add Fedora 4 database user
  postgresql_user:
    db: fcrepo
    name: fcrepo
    password: "{{ fedora4_postgresqldatabase_user_password }}"
    priv: ALL
    state: present
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

- name: Get the location of the pg_hba.conf file
  command: psql -t -P format=unaligned -c 'show hba_file'
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  register: hba_file
  changed_when: false

- name: Allow fedora4 user to connect to postgresl using password auth
  blockinfile:
    path: "{{ hba_file.stdout }}"
    insertafter: "^# TYPE  DATABASE        USER            ADDRESS                 METHOD"
    marker: "# {mark} Ansible Managed - Allow fedora4 user to connect using md5 auth"
    block: |
      host    fcrepo          fcrepo          127.0.0.1/32            md5
  notify: restart postgresql

- name: Run handlers to restart PostgreSQL if needed
  meta: flush_handlers

- name: Install Tomcat servlet container
  package:
    name: "{{ tomcat_package }}"
    state: present

- name: Install the Tomcat host manager and admin applications
  package:
    name: "{{ tomcat_admin_package }}"
    state: present

- name: Set setsebool nis_enabled on
  command: /usr/sbin/setsebool -P nis_enabled on
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: Overwrite the Tomcat users file
  template:
    src: tomcat-users.xml
    dest: "{{ tomcat_users_conf_path }}"
    owner: root
    group: "{{ tomcat_group }}"
    mode: u=r,g=r,o=
  notify: restart tomcat

- name: Make Fedora 4 data directory
  file:
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    state: directory
    path: /var/fedora4/data

- name: Create the Fedora 4 tomcat conf file which sets JAVA_OPTS
  template:
    src: fedora4.conf
    dest: "{{ tomcat_fedora4_conf_path }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: u=rx,g=,o=
  notify: restart tomcat

- name: Move the Fedora 4 warfile
  copy:
    src: fcrepo-webapp-4.7.5.war
    dest: "{{ tomcat_fedora4_war_path }}"
    owner: root
    group: "{{ tomcat_group }}"
    mode: u=r,g=r,o=r

- name: Start and enable the Tomcat service
  service:
    name: "{{ tomcat_service_name }}"
    state: started
    enabled: yes
