---
# Common tasks for all hosts

- name: Install vim
  package:
    name: vim
    state: present

- name: Install tree
  package:
    name: tree
    state: present

- name: Install curl
  package:
    name: curl
    state: present
