---
# Install Ruby

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - patch
    - curl
    - bzip2
    - tar

- name: Download ruby-install tarball
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
    dest: /tmp/ruby-install-0.7.0.tar.gz
    owner: root
    group: root
    mode: u=r,g=r,o=
    checksum: sha1:7c034d39e16910eddf9c4036feca1d8150fa5135

- name: Unarchive ruby-install into temp directory
  unarchive:
    remote_src: yes
    src: /tmp/ruby-install-0.7.0.tar.gz
    dest: /tmp
    creates: /tmp/ruby-install-0.7.0

- name: Install ruby-install
  command: make install
  args:
    chdir: /tmp/ruby-install-0.7.0
    creates: /usr/local/bin/ruby-install

- name: Install ruby
  command: /usr/local/bin/ruby-install ruby {{ ruby_version }} --sha1 {{ ruby_sha1_checksum }}
  args:
    chdir: /tmp/ruby-{{ ruby_version }}

- name: Download chruby tarball
  get_url:
    url: https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
    dest: /tmp/chruby-0.3.9.tar.gz
    owner: root
    group: root
    mode: u=r,g=r,o=
    checksum: sha1:64365226210f82b58092ed01a3fb57d379b99c80

- name: Unarchive chruby into temp directory
  unarchive:
    remote_src: yes
    src: /tmp/chruby-0.3.9.tar.gz
    dest: /tmp
    creates: /tmp/chruby-0.3.9

- name: Install chruby
  command: make install
  args:
    chdir: /tmp/chruby-0.3.9
    creates: /usr/local/bin/chruby-exec

- name: Add chruby globally
  copy:
    src: chruby.sh
    dest: /etc/profile.d/chruby.sh
    force: yes
    owner: root
    group: root
    mode: u=rx,g=rx,o=r
